services:

  source_db:
    image: postgres:15
    container_name: source_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SOURCE_DB_NAME}
      POSTGRES_USER: ${SOURCE_DB_USER}
      POSTGRES_PASSWORD: ${SOURCE_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - source_data:/var/lib/postgresql/data

  target_db:
    image: postgres:15
    container_name: target_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TARGET_DB_NAME}
      POSTGRES_USER: ${TARGET_DB_USER}
      POSTGRES_PASSWORD: ${TARGET_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - target_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api
    restart: always
    depends_on:
      - source_db
    env_file:
      - .env
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./api:/app

  etl:
    build: ./etl
    container_name: etl_container
    restart: always
    depends_on:
      - api
      - target_db
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./etl:/app

  dagster:
    build: ./dagster
    container_name: dagster_web
    restart: always
    depends_on:
      - source_db
      - target_db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./etl:/app/etl
      - ./dagster:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  source_data:
  target_data: